name: Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - run: corepack enable
      - run: npm ci
      - run: npm run build
      - uses: actions/github-script@v7
        with:
          script: |-
            import { readdir, mkdir, rename } from 'node:fs/promise';

            await mkdir('docs', { recursive: true });

            for (const { isDirectory, name } of await readdir('apps', { withFileTypes: true })) {
              if (isDirectory()) {
                await rename(`apps/${name}/dist`, `docs/${name}`);
                console.log(`Moved ${name}/dist to docs/${name}`);
              }
            }
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployments.outputs.page_url }}
    steps:
      - id: deployments
        uses: actions/deploy-pages@v4
